name: InAccel
on: workflow_dispatch
jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Get branch names
      id: branch-names
      uses: tj-actions/branch-names@v6
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Docker Metadata [Controller]
      id: controller-meta
      uses: docker/metadata-action@v4
      with:
        images: inaccel/kserve-controller
        labels: |
          org.opencontainers.image.authors=InAccel <info@inaccel.com>
          org.opencontainers.image.url=https://inaccel.com
          org.opencontainers.image.vendor=InAccel
        tags: ${{ steps.branch-names.outputs.current_branch }}
    - name: Build and push [Controller]
      uses: docker/build-push-action@v3
      with:
        labels: ${{ steps.controller-meta.outputs.labels }}
        push: true
        tags: ${{ steps.controller-meta.outputs.tags }}
    - name: Docker Metadata [Storage Initializer]
      id: storage-initializer-meta
      uses: docker/metadata-action@v4
      with:
        images: inaccel/kserve-storage-initializer
        labels: |
          org.opencontainers.image.authors=InAccel <info@inaccel.com>
          org.opencontainers.image.url=https://inaccel.com
          org.opencontainers.image.vendor=InAccel
        tags: ${{ steps.branch-names.outputs.current_branch }}
    - name: Build and push [Storage Initializer]
      uses: docker/build-push-action@v3
      with:
        context: python
        file: python/storage-initializer.Dockerfile
        labels: ${{ steps.storage-initializer-meta.outputs.labels }}
        push: true
        tags: ${{ steps.storage-initializer-meta.outputs.tags }}
